Liuba/Add NotFoundPage/Add img.four and zero/Adaptive NotFoundPage.
Cristosic/Garden-Project pull request #41
Opened 2024-05-15 21:15 UTC by Liuba1986

2024-05-16 13:43 UTC, Cristosic approved these changes

2024-05-16 14:11 UTC, ViktorGladkich requested changes

2024-05-16 14:11 UTC, ViktorGladkich commented on src/pages/NotFoundPage/NotFoundPage.jsx
> +          We’re sorry, the page you requested could not be found. <br /> Please
не используй тег br, оберни лучше в span строчку "Please go back to the homepage" и стилизуй span

2024-05-16 14:11 UTC, ViktorGladkich commented on src/pages/NotFoundPage/NotFoundPage.jsx
> +  const navigate = useNavigate();
я не сталкивался с хуком useNavigate, я бы реализовал переход на домашнюю страницу с помощью обычного Link "для кнопки"

2024-05-16 14:11 UTC, ViktorGladkich commented on src/components/DiscountForm/FormDiscount/FormDiscount.module.scss
> +  * {
не используй универсальный селектор *{}, он уже есть в App.scss

2024-05-16 15:26 UTC, Liuba1986 commented on src/pages/NotFoundPage/NotFoundPage.jsx
> +          We’re sorry, the page you requested could not be found. <br /> Please
Цель использования тег BR в для этой строчки было не дублировать процесс, поскольку это строчка является частью одного параграфа который согласно макету в фигме так и описан. То есть для одного параграфа нет необходимости обернуть в спан и ещё и стилизовать  два раза. С помощью тега Br мы переносим данную строку на новый ряд.

2024-05-16 16:31 UTC, ViktorGladkich approved these changes

2024-05-16 16:38 UTC, ViktorGladkich requested changes

2024-05-16 16:38 UTC, ViktorGladkich commented on src/pages/NotFoundPage/NotFoundPage.module.css
> +    width: 12.5%;
проверь совпадают размеры  как на фигме

2024-05-16 16:45 UTC, Liuba1986 commented on src/pages/NotFoundPage/NotFoundPage.module.css
> +    width: 12.5%;
Да, соответствует. Я использовала % чтобы плавно уменьшить размер изображения.

2024-05-16 16:57 UTC, ViktorGladkich requested changes

2024-05-16 16:57 UTC, ViktorGladkich commented on src/pages/NotFoundPage/NotFoundPage.jsx
> +          We’re sorry, the page you requested could not be found. <br /> Please
При добавлении <br /> в код становится сложнее управлять и поддерживать верстку, особенно в больших проектах. В твоем случаи может быть и не как и не влияет на управления внешним видом, но это считается плохой практикой использовать br даже из преподавателей кто то это говорил!

2024-05-16 18:04 UTC, ViktorGladkich approved these changes

2024-05-16 18:05 UTC, ViktorGladkich approved these changes

2024-05-16 18:05 UTC, ViktorGladkich approved these changes

2024-05-16 18:07 UTC, ViktorGladkich approved these changes

2024-05-17 10:15 UTC, ViktorGladkich approved these changes

2024-05-17 15:54 UTC, ViktorGladkich commented on src/components/DiscountForm/FormDiscount/FormDiscount.module.scss
> +  box-sizing: border-box;
padding: 0; и box-sizing: border-box; не нужно тут

2024-05-17 15:54 UTC, ViktorGladkich approved these changes

2024-05-17 15:54 UTC, merged